In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# Enter an r by c matrix M (r and c being the positive integers)

#r = 3
#c = 2
M = np.array([[2,2,1], [2,1,4], [3,1,2]])

In [3]:
# Display M in matrix format

print("Matrix M :")
print(M)

Matrix M :
[[2 2 1]
 [2 1 4]
 [3 1 2]]


In [4]:
# Display the rows and columns of the matrix M

print("Row of M:")
for row in M:
    print(row)
   
print("Column of M:")
for col in M.T:
    print(col)

Row of M:
[2 2 1]
[2 1 4]
[3 1 2]
Column of M:
[2 2 3]
[2 1 1]
[1 4 2]


In [5]:
# Find the scalar multiplication of M for a given scalar

scalar = 2
M_scalar = scalar*M
print(f"M multiplied by {scalar} :")
print(M_scalar)

M multiplied by 2 :
[[4 4 2]
 [4 2 8]
 [6 2 4]]


In [6]:
#  Find the transpose of the matrix M

M_transpose = M.T
print("Transpose of M :")
print(M_transpose)

Transpose of M :
[[2 2 3]
 [2 1 1]
 [1 4 2]]
