In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# Find the vector-matrix multiplication of a r by c matrix M with an c vector u

M = [[2,3,1], [7,5,2], [3,2,1]]
u = [1,2,1]
M_u = [sum([M[i][j] * u[j] for j in range(len(u))]) for i in range(len(M))]
print("Vector-matrix product of M with u:")
print(M_u)

Vector-matrix product of M with u:
[9, 19, 8]


In [3]:
# Find the matrix-matrix product of M with a c by p matrix N

N = [[1,4,1],[3,1,2],[1,2,1]]
M_N = np.dot(M,N)
print("Matrix-Matrix product of M with N:")
print(M_N)

Matrix-Matrix product of M with N:
[[12 13  9]
 [24 37 19]
 [10 16  8]]
